### ISSUE TITLE
exit builtin does not trigger program's defer statements

### ISSUE THREAD

**Issue by matttproud** [elves/elvish#1377]
I was prototyping with elvish today as a part of an experiment, and I noticed that `exit` builtin in the interactive shell as opposed to `^D` bypasses `defer` statements in `prog.Run`, like [this one for pprof](https://github.com/elves/elvish/blob/659bd5fa68d4b61a6c916f2cafca360c9e37482b/pkg/prog/prog.go#L122).  This is because, `^D` appears to [cause `Program.Run` to return](https://github.com/elves/elvish/blob/659bd5fa68d4b61a6c916f2cafca360c9e37482b/pkg/prog/prog.go#L148), presumably due to `io.EOF`; whereas [`exit`](https://github.com/elves/elvish/blob/9a576529a3029a29d6ca68607f5088e90a2e60eb/pkg/eval/builtin_fn_cmd.go#L110) calls `os.Exit`, which [bypasses any defers](https://changelog.com/gotime/165).

Is this behavior intentional, or is it a bug?  If this is a bug, I would propose solving it by propagating a structured error value from `eval.exit` that parent callers could handle, presumably [around here](https://github.com/elves/elvish/blob/9a576529a3029a29d6ca68607f5088e90a2e60eb/pkg/prog/prog.go#L146) in `prog.Run`, assuming one does not already exist:

```
type ExitError struct {
  Code int
}

func (ExitError) Error() string { ... }
```

Would doing that make sense?  If so, I might be happy to look at fixing this.  I see some evidence that there is a RPC subsystem in here, so I presume that the error type might need to be serializable for that as well.

First time user of elvish, so apologize if I am misunderstanding something here.  From what I've seen, this is a very nicely written Go program and intriguing project.  By the way, is this the same @krader1961 from Platforms at Google?  If so, hello again!  I learned a lot working with your team.

**Comment by krader1961** [comment]
@matttproud, Yes, I was a senior SWE in Google's Platform group and remember you. Welcome to this project. I think you'll enjoy using, and possibly contributing to, Elvish. Approximately seven years ago I got fed up with the POSIX shell standard and zsh in particular. I switched to, and contributed lots of changes to, the [fish shell](https://fishshell.com/) for several years. I grew disaffected with fish when they started making gratuitous backward incompatible changes; especially since such changes were often implemented without any transition period. Looking around I considered several other non-traditional shells and settled on Elvish. Primarily because I liked that it was a) written in Go, b) had extremely high code quality, c) had good test coverage, and d) the concept of a "value stream" separate from the traditional "byte stream" was clearly a huge step in the right direction to a better shell.

FYI, If you decide to contribute changes you'll find that the critique by the project owner is even more rigorous than anything I, and probably you, experienced at Google. And I considered Google's code reviews to be considerably more rigorous than what I was accustomed to at my previous employer.

**Comment by krader1961** [comment]
> Is this behavior intentional, or is it a bug?

It could be either depending on how you define the behavior of the builtin [`exit`](https://elv.sh/ref/builtin.html#exit) command. That command does not, and should not, talk about the Go language implementation details. Having said that, it seems likely the current implementation exists because it just seemed like the obvious way to do it and most closely matched how other, POSIX, shells handle the `exit` command. It should be changed. Specifically by calling `panic()` with a specific type that holds the desired exit value and having the deferred panic handler call `os.Exit()` if that type is recovered rather than dumping a panic stack. See, for example, `handlePanic()` in *pkg/shell/interact.go*. TBD is whether that approach is compatible with pprof.

**Comment by matttproud** [comment]
Yeah, I definitely share your sentiments.  Unpredictable user-interactive latency in bash (thanks to operating system packages contributing surprising behavior in run-parts directories) put me over the edge one day, and I switched to MirBSD's `mksh` and never looked back.  That said, the shell is ripe for improvement. Powershell (in spite of its structured data) feels so heavyweight and un-UNIX like.  I think you folks might have found and made a sweet spot.

As for reviews, I can definitely appreciate and respect that, having been in the maintainer boat myself a few times.

I agree that `exit`'s contract shouldn't leak any of Go to users, nor probably would that be appropriate in most parts of the user-visible product surface (outside of plugins).  The basic observation I have is the teardown process for the internals of the shell probably shouldn't differ between `^D` and `exit` significantly, lest subtle bugs get introduced down the road with the implementation behavior relying on one path versus another.  I'll give your `panic` suggestion a review and see what I can come up with in the next few days.  I've rarely used `panic` directly for error propagation.  Was the decision to use it in the compile routines largely based on ergonomics of control flow?  I think I can see how that would make sense with most of the routines reading state as opposed to writing state (and leaving the door open for incomplete corruption).  Just want to check the reasoning, so I can apply it faithfully.

**Comment by krader1961** [comment]
@matttproud, The reason I mentioned the compile use-case was to provide a concrete example where Elvish differentiates between different types of panics. That use case is, obviously, not directly relevant to this issue since it applies to the compilation of an Elvish block of code rather than its execution. However, it does raise the question of whether we expect tools like `go tool pprof` to produce useful data when profiling code that results in a compilation error.

**Comment by krader1961** [comment]
This can be closed since it was resolved by the fix for #1605.

**Comment by xiaq** [comment]
The fix https://github.com/elves/elvish/commit/79207b39b6bc128f13ba0f461d7819aa6601667a was introduced for a different reason, I think the general point of the issue still stands.

Making `exit` panic with a specific value makes sense to me.

**Comment by xiaq** [comment]
Hmm, actually a special error value would be cleaner. The interpreter already propagates errors everywhere, it just needs to know to _not_ catch the special error value in exception handling and propagate it all the way to `Evaler.Eval`.
